Update chazer.yml

diff --git a/.github/workflows/chazer.yml b/.github/workflows/chazer.yml
--- a/.github/workflows/chazer.yml
+++ b/.github/workflows/chazer.yml
@@ -16,7 +16,7 @@ jobs:
           chmod +x chazer
 
       - name: Run Chazer Scan
-        run: ./chazer scan . --json > report.json
+        run: ./chazer scan . --json > report.json || (echo "Chazer scan failed" && exit 1)
 
       - name: Upload Report
         uses: actions/upload-artifact@v7   # النسخة الجديدة
@@ -37,10 +37,11 @@ jobs:
           chmod +x chazer
 
       - name: Run Chazer Prune
-        run: ./chazer prune . --batch
+        run: ./chazer prune . --batch || (echo "Chazer prune failed" && exit 1)
 
       - name: Commit and Push Changes
-        run: |
+        uses: actions/checkout@v7
+      - run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git add .
